const fn = require("./index.js")
console.log(fn(7))
console.log(fn(20))
console.log(fn(30))
console.log(fn(40))
console.log(fn(50))
console.log(fn(60))
console.log(fn(70))
console.log(fn(80))
console.log(fn(90))
console.log(fn(100))
