console.log("--- testing isMoveBigL ---")
isMoveBigL(0) === true ? console.log("pass") : console.warn("fail")
isMoveBigL(4) === false ? console.log("pass") : console.warn("fail")
isMoveBigL(6) === true ? console.log("pass") : console.warn("fail")
isMoveBigL(2) === false ? console.log("pass") : console.warn("fail")
isMoveBigL(1) === false ? console.log("pass") : console.warn("fail")
isMoveBigL(5) === false ? console.log("pass") : console.warn("fail")

console.log("--- testing findLittleLMoves ---")
JSON.stringify(findLittleLMoves([3, 1])) === "[[2,0],[2,2]]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findLittleLMoves([0, 1])) === "[[1,0],[1,2]]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findLittleLMoves([1, 1])) === "[[0,0],[0,2],[2,0],[2,2]]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findLittleLMoves([2, 2])) === "[[3,1],[1,1]]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findLittleLMoves([0, 0])) === "[[1,1]]" ? console.log("pass") : console.warn("fail")
