console.log("--- testing isMoveBigL ---")
isMoveBigL(0) === true ? console.log("pass") : console.warn("fail")
isMoveBigL(4) === false ? console.log("pass") : console.warn("fail")
isMoveBigL(6) === true ? console.log("pass") : console.warn("fail")
isMoveBigL(2) === false ? console.log("pass") : console.warn("fail")
isMoveBigL(1) === false ? console.log("pass") : console.warn("fail")
isMoveBigL(5) === false ? console.log("pass") : console.warn("fail")

console.log("--- testing findLMoves littleLMoves ---")
JSON.stringify(findLMoves([3, 1], littleLMoves).sort()) === "[[2,0],[2,2]]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findLMoves([0, 1], littleLMoves).sort()) === "[[1,0],[1,2]]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findLMoves([1, 1], littleLMoves).sort()) === "[[0,0],[0,2],[2,0],[2,2]]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findLMoves([2, 2], littleLMoves).sort()) === "[[1,1],[3,1]]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findLMoves([0, 0], littleLMoves).sort()) === "[[1,1]]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findLMoves([2, 1], littleLMoves).sort()) === "[[1,0],[1,2]]" ? console.log("pass") : console.warn("fail")

console.log("--- testing findLMoves bigLMoves ---")
JSON.stringify(findLMoves([3, 1], bigLMoves).sort()) === "[[1,0],[1,2]]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findLMoves([0, 1], bigLMoves).sort()) === "[[2,0],[2,2]]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findLMoves([1, 1], bigLMoves).sort()) === "[]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findLMoves([2, 2], bigLMoves).sort()) === "[[0,1],[1,0]]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findLMoves([0, 0], bigLMoves).sort()) === "[[1,2],[2,1]]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findLMoves([2, 1], bigLMoves).sort()) === "[[0,0],[0,2]]" ? console.log("pass") : console.warn("fail")

console.log("--- testing findPossiableNextMoves true ---")
JSON.stringify(findPossiableNextMoves(true, [[3, 1]]).sort()) === "[[1,0],[1,2]]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findPossiableNextMoves(true, [[3, 1],[1, 1]]).sort()) === "[[1,0],[1,2]]" ? console.log("pass") : console.warn("fail")
JSON.stringify(findPossiableNextMoves(true, [[3, 1],[1, 1],[0, 0]]).sort()) === "[[1,0],[1,2],[2,1]]" ? console.log("pass") : console.warn("fail")
